### PR TITLE
Update dependencies, etc

### PR DESCRIPTION
**Pull request by tusbar**
### Initial checklist

*   [x] I read the support docs 
*   [x] I read the contributing guide 
*   [x] I agree to follow the code of conduct 
*   [x] I searched issues and couldn’t find anything (or linked relevant results below) 
*   [x] If applicable, I’ve added docs and tests

### Description of changes

- Update dependencies to support usage with remark 15.
- Update outdated GH actions workflows.
- Update development dependencies.
- Move @types/* dependencies to development dependencies.
- Require node 16, update build scripts, remove rimraf.
- Use `RootContent` instead of deprecated `Content` type.

### CODE REVIEW

**Comment by tusbar** [comment]
These github actions workflows could be optimized ;)

**Comment by wooorm** [comment]
really appreciate you helping, but I’m working on this as fast as I can already. I’ll see if I can merge this though!

**Comment by tusbar** [comment]
I’ve updated the GH actions and dev dependencies.

**Comment by tusbar** [comment]
@wooorm I’ve updated a few more things, mimicking what you’ve done on other repos.

**Comment by leeweisberger** [comment]
Any chance someone can take a look at this... this is blocking us from updating all of our remark/rehype dependencies in our codebase (unless there's a workaround).

**Review by wooorm — APPROVED** [review]

**Comment by wooorm** [comment]
Thanks!

**Comment by wooorm** [comment]
[Released](https://github.com/remarkjs/strip-markdown/releases/tag/6.0.0)!

**Pull request merged**
